USE YELP;

INSERT INTO "YELP"."DWH"."CLIMATE"
SELECT * FROM "YELP"."ODS"."TEMP_AND_PERCIPTIATION";

INSERT INTO "YELP"."DWH"."BUSINESS"
SELECT * FROM "YELP"."ODS"."BUSINESS";

INSERT INTO "YELP"."DWH"."USER"
SELECT * FROM "YELP"."ODS"."USER";

INSERT INTO "YELP"."DWH"."TIP"
SELECT UUID_STRING() as TIP_ID, * FROM "YELP"."ODS"."TIP";

INSERT INTO "YELP"."DWH"."REVIEW"
SELECT * FROM "YELP"."ODS"."REVIEW";

INSERT INTO "YELP"."DWH"."CHECKIN"
SELECT BUSINESS_ID, DATE, COUNT(*) AS TOTAL_CHECKINS
FROM "YELP"."ODS"."CHECKIN"
GROUP BY BUSINESS_ID, DATE;

