USE YELP;

DROP TABLE ODS.TEMPERATURE;
DROP TABLE ODS.PRECIPITATION;
DROP TABLE ODS.USER;
DROP TABLE ODS.TIP;
DROP TABLE ODS.REVIEW;
DROP TABLE ODS.BUSINESS;
DROP TABLE ODS.CHECKIN;

CREATE TABLE ODS.PRECIPITATION (
    date DATE,
    precipitation FLOAT,
    precipitation_normal FLOAT
);

CREATE TABLE ODS.TEMPERATURE (
    date DATE,
    temperature_min FLOAT, 
    temperature_max FLOAT,
    temperature_normal_min FLOAT,
    temperature_normal_max FLOAT
);

CREATE TABLE ODS.USER (
    USER_ID VARCHAR,
    NAME VARCHAR(100),
    REVIEW_COUNT INT,
    USEFUL INT,
    FUNNY INT,
    YELPING_SINCE DATE
);

CREATE TABLE ODS.TIP (
    BUSINESS_ID VARCHAR,
    COMPLIMENT_COUNT INT,
    DATE DATE,
    TEXT VARCHAR, 
    USER_ID VARCHAR
);

CREATE TABLE ODS.REVIEW (
    BUSINESS_ID VARCHAR,
    REVIEW_ID VARCHAR,
    USER_ID VARCHAR,
    COOL INT,
    DATE DATE,
    FUNNY INT,
    STARS INT,
    TEXT VARCHAR,
    USEFUL INT
);

CREATE TABLE ODS.CHECKIN (
    BUSINESS_ID VARCHAR,
    DATE DATE
);

CREATE TABLE ODS.BUSINESS (
    ADDRESS VARCHAR,
    BUSINESS_ID VARCHAR,
    CATEGORIES  VARCHAR,
    CITY VARCHAR,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    NAME VARCHAR,
    POSTAL_CODE VARCHAR,
    REVIEW_COUNT INT,
    STARS INT,
    STATE VARCHAR
);

CREATE VIEW ODS.TEMP_AND_PERCIPTIATION AS
  SELECT ODS.TEMPERATURE.DATE, precipitation, precipitation_normal, temperature_min, temperature_max, temperature_normal_min, temperature_normal_max
  FROM ODS.PRECIPITATION 
  JOIN ODS.TEMPERATURE
  ON ODS.PRECIPITATION.DATE = ODS.TEMPERATURE.DATE;
  
CREATE VIEW ODS.WEATHER_AND_REVIEWS AS
  SELECT ODS.REVIEW.*, precipitation, precipitation_normal, temperature_min, temperature_max, temperature_normal_min, temperature_normal_max
  FROM ODS.TEMP_AND_PERCIPTIATION 
  JOIN ODS.REVIEW
  ON ODS.TEMP_AND_PERCIPTIATION.DATE = ODS.REVIEW.DATE;
  
  
  