USE YELP;

SELECT * FROM ODS.TEMPERATURE;
SELECT * FROM ODS.PRECIPITATION;

SELECT * FROM ODS.USER;
SELECT * FROM ODS.TIP;
SELECT * FROM ODS.REVIEW;
SELECT * FROM ODS.BUSINESS;
SELECT * FROM ODS.CHECKIN;

SELECT * FROM ODS.TEMP_AND_PERCIPTIATION;
SELECT * FROM ODS.WEATHER_AND_REVIEWS LIMIT 10;